# Generated by Django 3.0.4 on 2020-03-19 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('year', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('unit',
                 models.CharField(choices=[('kg', 'kilogram'), ('m', 'metr'), ('s', 'sekunda'), ('', '')], default='',
                                  max_length=2)),
                ('more_better', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                (
                'clazz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wyniki.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=4)),
                ('date', models.DateTimeField()),
                (
                'sport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wyniki.Sport')),
                ('student',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wyniki.Student')),
            ],
        ),
    ]
