# Generated by Django 3.0.4 on 2020-03-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wyniki', '0003_auto_20200322_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
