# Generated by Django 3.0.4 on 2020-03-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wyniki', '0004_auto_20200322_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='more_better',
            field=models.BooleanField(default=True),
        ),
    ]
