# Generated by Django 3.0.4 on 2020-03-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wyniki', '0005_auto_20200322_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='group',
            field=models.CharField(choices=[('1', 'Klasa I'), ('2', 'Klasa II'), ('3', 'Klasa III')], default='1',
                                   max_length=20),
        ),
    ]
