# Generated by Django 3.0.4 on 2020-03-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wyniki', '0006_auto_20200325_1842'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.AlterField(
            model_name='result',
            name='group',
            field=models.CharField(choices=[('FIRST', 'Klasa I'), ('SECOND', 'Klasa II'), ('THIRD', 'Klasa III')],
                                   default='FIRST', max_length=20),
        ),
    ]
