# Generated by Django 3.0.4 on 2020-03-27 08:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('wyniki', '0007_auto_20200325_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name', 'first_name']},
        ),
    ]
