# Generated by Django 3.0.4 on 2020-04-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wyniki', '0008_auto_20200327_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
