# Generated by Django 3.0.4 on 2020-04-08 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wyniki', '0009_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='year',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(2010),
                                                       django.core.validators.MaxValueValidator(2030)]),
        ),
        migrations.AlterField(
            model_name='result',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=6,
                                      validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
